apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
  namespace: cicd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
        - name: app
          image: abhi20242024/cicd:latest
          ports:
            - containerPort: 80